# Generated by Django 4.1.7 on 2023-06-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustable',
            name='NameOfDevice',
            field=models.CharField(default=8192, max_length=50),
            preserve_default=False,
        ),
    ]
