# Generated by Django 4.1.7 on 2023-06-14 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_app', '0002_statustable_nameofdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustable',
            name='TimeIs',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
