# Generated by Django 4.1.7 on 2023-06-16 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_app', '0003_statustable_timeis'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTabletwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagStatus8192', models.CharField(max_length=50)),
                ('TagStatus8193', models.CharField(max_length=50)),
                ('TimeIs', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
