# Generated by Django 4.1.7 on 2023-06-17 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_app', '0005_statustabletwo_tagstatus8194_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTable8192',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagStatus', models.CharField(max_length=50)),
                ('NameOfDevice', models.CharField(max_length=50)),
                ('TimeIs', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='StatusTable8193',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagStatus', models.CharField(max_length=50)),
                ('NameOfDevice', models.CharField(max_length=50)),
                ('TimeIs', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='StatusTable8194',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagStatus', models.CharField(max_length=50)),
                ('NameOfDevice', models.CharField(max_length=50)),
                ('TimeIs', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
