# Generated by Django 4.1.7 on 2023-06-17 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_app', '0006_statustable8192_statustable8193_statustable8194'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTable8195',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagStatus', models.CharField(max_length=50)),
                ('NameOfDevice', models.CharField(max_length=50)),
                ('TimeIs', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
