# Generated by Django 4.1.7 on 2023-06-24 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_app', '0007_statustable8195'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTable8196',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagStatus', models.CharField(max_length=50)),
                ('NameOfDevice', models.CharField(max_length=50)),
                ('TimeIs', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='StatusTable8197',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagStatus', models.CharField(max_length=50)),
                ('NameOfDevice', models.CharField(max_length=50)),
                ('TimeIs', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='StatusTable8198',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagStatus', models.CharField(max_length=50)),
                ('NameOfDevice', models.CharField(max_length=50)),
                ('TimeIs', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
